name: map_fire
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.12.9
  permission_handler: ^5.1.0+2
  firebase_auth: ^0.16.0
  google_sign_in: ^4.2.0
  shimmer: ^1.1.2

  #GEOLOCATION
  geolocator: ^6.1.13
  geocoder: ^0.2.1
  http: ^0.12.0+2
  flutter_map: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/