name: bf_timeline
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: "0.15.4"
  firebase_core: ^0.4.0+9
  font_awesome_flutter:
  provider:
  google_sign_in: ^4.4.4
  cloud_firestore: "0.13.4+2"

  #OTHERS
  flutter_spinkit: ^4.1.2
  modal_progress_hud: ^0.1.3
  google_fonts: ^1.1.0
  image_picker: "0.6.3+4"
  percent_indicator: "^2.1.1"
  share: ^0.6.2+3
  permission_handler:
  agora_rtc_engine:
  timeago: ^2.0.26
  cupertino_icons: ^0.1.3
  uuid: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


    - family: Palanquin
      fonts:
        - asset: assets/fonts/palanquin/palanquin-regular.ttf